### ISSUE TITLE
Auth failed

### ISSUE THREAD

**Issue by HepoH3** [ClusterM/skykettle-ha#1]
Hi, thank you for your integration!
I was able to add RK-G213S kettle to the integration, but everything is inactive and there is an error in the logs:
>Auth failed. You need to enable pairing mode on the kettle.

While I already enabled pairing mode and pair was successful. Actually there is a stale [integration](https://github.com/mavrikkk/ha_kettler) that kinda worked (but inconsistently). And this integration needed to send any 8-byte password, maybe that's the problem? 
![](https://puu.sh/IFJJx/f2781c7900.png)

**Comment by ClusterM** [comment]
Hi!
Which logging level did you set? Can you set it to "debug" and send me logs? Password should be generated automatically.

**Comment by HepoH3** [comment]
@ClusterM, sure, right after get back from work.

**Comment by HepoH3** [comment]
Okay, so I have following logger config:
```
logger:
  default: warning
  logs:
    custom_components.webrtc: debug
    custom_components.skykettle: debug
```
Nothing changed, error still the same and I don't see any additional info, but maybe traceback will help you.

> Logger: custom_components.skykettle.kettle_connection
> Source: custom_components/skykettle/kettle_connection.py:146
> Integration: SkyKettle (documentation, issues)
> First occurred: 21:52:44 (1 occurrences)
> Last logged: 21:52:44
> 
> Auth failed. You need to enable pairing mode on the kettle.

**Comment by HepoH3** [comment]
Okay, so I found `home-assistant.log` file with the following content:

> 2022-02-01 00:02:08 DEBUG (MainThread) [custom_components.skykettle.config_flow] Scan result: [BleDevice(mac='ED:99:2C:79:90:A3', name='RFS-KKL004'), BleDevice(mac='7D:B4:54:3E:62:51', name=None), BleDevice(mac='E1:73:84:D1:67:ED', name=None), BleDevice(mac='58:B6:23:50:46:09', name=None), BleDevice(mac='A4:C1:38:4E:45:52', name=None)]
> 2022-02-01 00:02:09 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Updating
> 2022-02-01 00:02:09 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Staring gatttool...
> 2022-02-01 00:02:09 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Started gatttool
> 2022-02-01 00:02:10 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Attempting to connect...
> 2022-02-01 00:02:10 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Connected to the Kettle
> 2022-02-01 00:02:10 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command ff, data: [3e 7e a9 23 b2 dc f6 6f]
> 2022-02-01 00:02:10 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 00
> 2022-02-01 00:02:10 DEBUG (MainThread) [custom_components.skykettle.skykettle] Auth: ok=False
> 2022-02-01 00:02:10 WARNING (MainThread) [custom_components.skykettle.kettle_connection] Auth failed. You need to enable pairing mode on the kettle.
> 2022-02-01 00:02:10 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Disconnected
> 2022-02-01 00:02:10 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Terminated
> 2022-02-01 00:02:10 INFO (MainThread) [custom_components.skykettle.kettle_connection] Disposed.
> 2022-02-01 00:02:16 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Updating
> 2022-02-01 00:02:16 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Staring gatttool...
> 2022-02-01 00:02:16 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Started gatttool
> 2022-02-01 00:02:16 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Attempting to connect...
> 2022-02-01 00:02:17 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Connected to the Kettle
> 2022-02-01 00:02:17 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command ff, data: [3e 7e a9 23 b2 dc f6 6f]
> 2022-02-01 00:02:17 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 01
> 2022-02-01 00:02:17 DEBUG (MainThread) [custom_components.skykettle.skykettle] Auth: ok=True
> 2022-02-01 00:02:17 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Auth ok
> 2022-02-01 00:02:17 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 6e, data: [59 4e f8 61 30 2a 00 00]
> 2022-02-01 00:02:18 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 00
> 2022-02-01 00:02:18 DEBUG (MainThread) [custom_components.skykettle.skykettle] Writed time=1643662937 (2022-02-01 00:02:17), offset=10800 (GMT+3.00)
> 2022-02-01 00:02:18 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 01, data: []
> 2022-02-01 00:02:18 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 03 09
> 2022-02-01 00:02:18 DEBUG (MainThread) [custom_components.skykettle.skykettle] Version: 3.9
> 2022-02-01 00:02:18 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 06, data: []
> 2022-02-01 00:02:18 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 00 00 00 00 01 50 0f 00 00 00 00 00 00 80 00 00
> 2022-02-01 00:02:18 DEBUG (MainThread) [custom_components.skykettle.skykettle] Status: mode=0 (Boil), is_on=False, target_temp=0, current_temp=80, sound_enabled=True, color_interval=15, boil_time=0
> 2022-02-01 00:02:18 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 47, data: [00]
> 2022-02-01 00:02:18 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 00 00 e7 77 08 00 d4 2c 05 00 4f 0e 00 00 00 00
> 2022-02-01 00:02:18 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 50, data: [00]
> 2022-02-01 00:02:18 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 00 00 00 4e 0e 00 00 00 00 00 00 00 00 00 00 00
> 2022-02-01 00:02:18 DEBUG (MainThread) [custom_components.skykettle.skykettle] Stats: ontime=6 days, 10:09:43, energy_wh=339156, user_on_count=3662, heater_on_count=3663
> 2022-02-01 00:02:18 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 35, data: [00]
> 2022-02-01 00:02:19 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 00 00 01 00 00
> 2022-02-01 00:02:19 DEBUG (MainThread) [custom_components.skykettle.skykettle] Light with type=0 (boiling_light) is on
> 2022-02-01 00:02:19 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 35, data: [c8]
> 2022-02-01 00:02:19 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: c8 00 00 c8 00
> 2022-02-01 00:02:19 DEBUG (MainThread) [custom_components.skykettle.skykettle] Light with type=200 (sync_light) is off
> 2022-02-01 00:02:19 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 30, data: []
> 2022-02-01 00:02:19 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 08 00
> 2022-02-01 00:02:19 DEBUG (MainThread) [custom_components.skykettle.skykettle] Lamp auto off hours=8
> 2022-02-01 00:02:19 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 52, data: [00]
> 2022-02-01 00:02:19 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 00 00 30 00 00 00 00 00 00 00 00 00 00 00 00 00
> 2022-02-01 00:02:19 DEBUG (MainThread) [custom_components.skykettle.skykettle] Fresh water notification is off, unknown1=48, water_freshness_hours=0
> 2022-02-01 00:02:19 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 33, data: [00]
> 2022-02-01 00:02:19 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 00 23 ff 00 00 ff 46 ff 00 ff 00 64 ff ff 00 00
> 2022-02-01 00:02:19 DEBUG (MainThread) [custom_components.skykettle.skykettle] ColorsSet(light_type=0, temp_low=35, brightness=255, r_low=0, g_low=0, b_low=255, temp_mid=70, unknown1=255, r_mid=0, g_mid=255, b_mid=0, temp_high=100, unknown2=255, r_high=255, g_high=0, b_high=0)
> 2022-02-01 00:02:19 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 33, data: [01]
> 2022-02-01 00:02:19 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 01 00 7f 00 00 ff 32 7f 00 ff 00 64 7f ff 00 00
> 2022-02-01 00:02:19 DEBUG (MainThread) [custom_components.skykettle.skykettle] ColorsSet(light_type=1, temp_low=0, brightness=127, r_low=0, g_low=0, b_low=255, temp_mid=50, unknown1=127, r_mid=0, g_mid=255, b_mid=0, temp_high=100, unknown2=127, r_high=255, g_high=0, b_high=0)
> 2022-02-01 00:02:19 INFO (MainThread) [custom_components.skykettle.kettle_connection] Disposed.
> 2022-02-01 00:02:21 INFO (MainThread) [custom_components.skykettle.config_flow] Config saved
> 2022-02-01 00:02:21 ERROR (MainThread) [custom_components.xiaomi_miot.camera] kamera Camera Control: Got MiioException while fetching the state: {'code': -10000, 'message': 'user undefined error'}, mapping: {'camera_control.on': {'siid': 2, 'piid': 1}, 'camera_control.image_rollover': {'siid': 2, 'piid': 2}, 'camera_control.night_shot': {'siid': 2, 'piid': 3}, 'camera_control.time_watermark': {'siid': 2, 'piid': 4}, 'camera_control.wdr_mode': {'siid': 2, 'piid': 5}, 'glimmer_full_color-2-6': {'siid': 2, 'piid': 6}, 'camera_control.recording_mode': {'siid': 2, 'piid': 7}, 'camera_control.motion_tracking': {'siid': 2, 'piid': 8}, 'stream_status-3-1': {'siid': 3, 'piid': 1}}, max_properties: 10/9
> 2022-02-01 00:02:22 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Updating
> 2022-02-01 00:02:22 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Staring gatttool...
> 2022-02-01 00:02:22 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Started gatttool
> 2022-02-01 00:02:22 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Attempting to connect...
> 2022-02-01 00:02:22 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Connected to the Kettle
> 2022-02-01 00:02:22 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command ff, data: [3e 7e a9 23 b2 dc f6 6f]
> 2022-02-01 00:02:22 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 01
> 2022-02-01 00:02:22 DEBUG (MainThread) [custom_components.skykettle.skykettle] Auth: ok=True
> 2022-02-01 00:02:22 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Auth ok
> 2022-02-01 00:02:22 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 6e, data: [5e 4e f8 61 30 2a 00 00]
> 2022-02-01 00:02:22 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 00
> 2022-02-01 00:02:22 DEBUG (MainThread) [custom_components.skykettle.skykettle] Writed time=1643662942 (2022-02-01 00:02:22), offset=10800 (GMT+3.00)
> 2022-02-01 00:02:22 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 01, data: []
> 2022-02-01 00:02:23 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 03 09
> 2022-02-01 00:02:23 DEBUG (MainThread) [custom_components.skykettle.skykettle] Version: 3.9
> 2022-02-01 00:02:23 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 06, data: []
> 2022-02-01 00:02:23 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 00 00 00 00 01 50 0f 00 00 00 00 00 00 80 00 00
> 2022-02-01 00:02:23 DEBUG (MainThread) [custom_components.skykettle.skykettle] Status: mode=0 (Boil), is_on=False, target_temp=0, current_temp=80, sound_enabled=True, color_interval=15, boil_time=0
> 2022-02-01 00:02:23 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 47, data: [00]
> 2022-02-01 00:02:23 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 00 00 e7 77 08 00 d4 2c 05 00 4f 0e 00 00 00 00
> 2022-02-01 00:02:23 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 50, data: [00]
> 2022-02-01 00:02:23 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 00 00 00 4e 0e 00 00 00 00 00 00 00 00 00 00 00
> 2022-02-01 00:02:23 DEBUG (MainThread) [custom_components.skykettle.skykettle] Stats: ontime=6 days, 10:09:43, energy_wh=339156, user_on_count=3662, heater_on_count=3663
> 2022-02-01 00:02:23 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 35, data: [00]
> 2022-02-01 00:02:23 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 00 00 01 00 00
> 2022-02-01 00:02:23 DEBUG (MainThread) [custom_components.skykettle.skykettle] Light with type=0 (boiling_light) is on
> 2022-02-01 00:02:23 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 35, data: [c8]
> 2022-02-01 00:02:24 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: c8 00 00 c8 00
> 2022-02-01 00:02:24 DEBUG (MainThread) [custom_components.skykettle.skykettle] Light with type=200 (sync_light) is off
> 2022-02-01 00:02:24 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 30, data: []
> 2022-02-01 00:02:24 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 08 00
> 2022-02-01 00:02:24 DEBUG (MainThread) [custom_components.skykettle.skykettle] Lamp auto off hours=8
> 2022-02-01 00:02:24 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 52, data: [00]
> 2022-02-01 00:02:24 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 00 00 30 00 00 00 00 00 00 00 00 00 00 00 00 00
> 2022-02-01 00:02:24 DEBUG (MainThread) [custom_components.skykettle.skykettle] Fresh water notification is off, unknown1=48, water_freshness_hours=0
> 2022-02-01 00:02:24 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 33, data: [00]
> 2022-02-01 00:02:24 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 00 23 ff 00 00 ff 46 ff 00 ff 00 64 ff ff 00 00
> 2022-02-01 00:02:24 DEBUG (MainThread) [custom_components.skykettle.skykettle] ColorsSet(light_type=0, temp_low=35, brightness=255, r_low=0, g_low=0, b_low=255, temp_mid=70, unknown1=255, r_mid=0, g_mid=255, b_mid=0, temp_high=100, unknown2=255, r_high=255, g_high=0, b_high=0)
> 2022-02-01 00:02:24 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 33, data: [01]
> 2022-02-01 00:02:24 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 01 00 7f 00 00 ff 32 7f 00 ff 00 64 7f ff 00 00
> 2022-02-01 00:02:24 DEBUG (MainThread) [custom_components.skykettle.skykettle] ColorsSet(light_type=1, temp_low=0, brightness=127, r_low=0, g_low=0, b_low=255, temp_mid=50, unknown1=127, r_mid=0, g_mid=255, b_mid=0, temp_high=100, unknown2=127, r_high=255, g_high=0, b_high=0)
> 
It seems that integration fails to auth while pairing, but able to authorize right after that.

**Comment by ClusterM** [comment]
Log says that it's connected to the kettle and works fine. But integration disabled in HA for some reason. Maybe it's because of conflict with another Redmond integration. I see logo of other integration on the screenshot. Try to reenable another integration and completely delete it first.

**Comment by HepoH3** [comment]
> Log says that it's connected to the kettle and works fine. But integration disabled in HA for some reason. Maybe it's because of conflict with another Redmond integration. I see logo of other integration on the screenshot. Try to reenable another integration and completely delete it first.

That's right! Thank you!
