### ISSUE TITLE
Как включить на обогрев в автоматизации?

### ISSUE THREAD

**Issue by TonTon-Macout** [ClusterM/skykettle-ha#10]
Включить выключить получилось, а как подогреть до заданной температуры?

**Comment by ClusterM** [comment]
Через entity типа `water_heater`:

![image](https://user-images.githubusercontent.com/4236181/155293333-9d0b35be-2c06-4365-89d3-8b39823c72ec.png)

Режимы:
* Boil - кипячение
* Boil+Heat - кипячение, а потом поддержание заданной температуры
* Heat - просто поддержание заданной температуры

Если просто выставить температуру, когда чайник выключен, он автоматически перейдёт в режим Heat.

**Comment by TonTon-Macout** [comment]
Чето пока не отдуплю никак) 
Пробую через UI, создать автоматизацию - доваить действие - текстовый редактор.
Если выставлю так температуру, она меняется но подогрев не включается
```
device_id: d2c877ea3e4df25380f71f029b4960fb
domain: number
entity_id: number.skykettle_rk_g210_temperature_3
type: set_value
value: 85
```

а если так: 
```
device_id: d2c877ea3e4df25380f71f029b4960fb
domain: water_heater
entity_id: water_heater.skykettle_rk_g210
type: turn_on
```
то включается кипячение,  и чего я сюда не приписываю всевремя ругается что нет такого extra

**Comment by TonTon-Macout** [comment]
Спасибо! Заработало! 
Ага, хорошо бы вынести. 
Я целый день все в устройства тыкал и ни как не мог понять что не так делаю)
