### ISSUE TITLE
Мультиварка?

### ISSUE THREAD

**Issue by Psytoshgen** [ClusterM/skykettle-ha#12]
Подскажите, можно ли при помощи компонента прикрутить мультиварку? полная подержка программ не принципиальна, хотя бы базовый функционал.
RMC-M223S - старушка работает исправно, и еще будет лет цать работать, но всё что находил из интеграций по R4S либо умерло, либо на пути туда. Если нужно что-то, могу попробовать выдернуть. Пока есть обнаруженный девайс через BLE.
![cc052ace58b22db01d4a23ffd9207540-53997193](https://user-images.githubusercontent.com/94195788/157890611-2146c29b-903c-4906-bbd4-71838a050e55.jpg)

Так же вот эту интеграцию нашел, но так и не понял как сопряжение организовать и где ключ выдернуть.
https://github.com/mavrikkk/ha_kettler

**Comment by ClusterM** [comment]
Это надо иметь девайс под рукой, чтобы реверсить...

**Comment by Psytoshgen** [comment]
Подскажите хоть в какую сторону рыть в поиске ключа. По сути работает так же как и чайник, только минус иллюминация

**Comment by ClusterM** [comment]
> Подскажите хоть в какую сторону рыть в поиске ключа. По сути работает так же как и чайник, только минус иллюминация

Сниффать блютус трафик официального приложения и смотреть, какие команды там посылаются.

**Comment by Psytoshgen** [comment]
с ключом решилось просто, https://crypt-online.ru/crypts/text2hex/ 
8 символов, перевел в hex ascii

теперь думаю как это вписать в ваш код


COOKER_PROGRAMS = {
    'Рис':['01', '00', '64', '00', '23','00','00','01'],
    'Томление':['02', '00', '61', '03', '00','00','00','01'],
    'Плов':['03', '00', '6e', '01', '00','00','00','01'],
    'Жареные_овощи':['04', '01', 'b4', '00', '12','00','00','01'],
    'Жареная_рыба':['04', '02', 'b4', '00', '0c','00','00','01'],
    'Жареное_мясо':['04', '03', 'b4', '00', '0f','00','00','01'],
    'Тушеные_овощи':['05', '01', '64', '00', '28','00','00','01'],
    'Тушеная_рыба':['05', '02', '64', '00', '23','00','00','01'],
    'Тушеное_мясо':['05', '03', '64', '01', '00','00','00','01'],
    'Паста':['06', '00', '64', '00', '08','00','00','01'],
    'Молочная_каша':['07', '00', '5f', '00', '23','00','00','01'],
    'Суп':['08', '00', '63', '01', '00','00','00','01'],
    'Йогурт':['09', '00', '28', '08', '00','00','00','00'],
    'Выпечка':['0a', '00', '91', '00', '2d','00','00','01'],
    'Овощи_на_пару':['0b', '01', '64', '00', '1e','00','00','01'],
    'Рыба_на_пару':['0b', '02', '64', '00', '19','00','00','01'],
    'Мясо_на_пару':['0b', '03', '64', '00', '28','00','00','01'],
    'Разогрев':['0c', '00', '64', '00', '28','00','00','01']}

**Comment by ClusterM** [comment]
Было решено остановиться на чайниках.
