### ISSUE TITLE
skykettle.number::SkyNumber

### ISSUE THREAD

**Issue by SergeyBakinskiy** [ClusterM/skykettle-ha#18]
Logger: homeassistant.components.number
Source: components/number/__init__.py:220
Integration: Число 
First occurred: 02:49:56 (1 occurrences)
Last logged: 02:49:56

custom_components.skykettle.number::SkyNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom component author.

**Comment by ClusterM** [comment]
Fixed.
