### ISSUE TITLE
Unknown kettle model.

### ISSUE THREAD

**Issue by SergeyBakinskiy** [ClusterM/skykettle-ha#22]
Эта ошибка возникла в кастомной интеграции.

Logger: homeassistant.config_entries
Source: custom_components/skykettle/skykettle.py:117
Integration: SkyKettle (documentation, issues)
First occurred: 20:44:10 (1 occurrences)
Last logged: 20:44:10

Error setting up entry RFS-KKL00 (C9:39:93:22:77:0D) for skykettle
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/skykettle/__init__.py", line 41, in async_setup_entry
    kettle = KettleConnection(
  File "/config/custom_components/skykettle/kettle_connection.py", line 26, in __init__
    super().__init__(model)
  File "/config/custom_components/skykettle/skykettle.py", line 117, in __init__
    raise SkyKettleError("Unknown kettle model")
custom_components.skykettle.skykettle.SkyKettleError: 
Unknown kettle model

**Comment by Kvasenok** [comment]
Точно такая же ошибка (только мак другой). Модель чайника RK-G213S.

**Comment by ClusterM** [comment]
Попробуйте удалить и добавить заново интеграцию.

**Comment by TischenkoArseny** [comment]
Такая же ошибка, также же чайник определяется как RFS-KKL00. Модель RK-G211S, добавил         "RFS-KKL00": MODELS_4, в skykettle.py, всё заработало.

**Comment by HepoH3** [comment]
> Точно такая же ошибка (только мак другой). Модель чайника RK-G213S.

Модель [уже указана](https://github.com/ClusterM/skykettle-ha/blob/master/custom_components/skykettle/skykettle.py#L35), так что странно, что у вас есть эта ошибка

**Comment by SergeyBakinskiy** [comment]
> Попробуйте удалить и добавить заново интеграцию. Если проблема сохранится, скиньте лог заново.

После перестановки интеграции, проблема решилась.

**Comment by ClusterM** [comment]
> > Точно такая же ошибка (только мак другой). Модель чайника RK-G213S.
> 
> Модель [уже указана](https://github.com/ClusterM/skykettle-ha/blob/master/custom_components/skykettle/skykettle.py#L35), так что странно, что у вас есть эта ошибка

Там в предыдущих версиях был баг, из-за которых обрезалось название модели чайника.

**Comment by HepoH3** [comment]
Тоже пришлось переустановить интеграцию и добавить модель "RFS-KKL004": MODELS_4. Наверное это в breaking changes вынести стоит.

**Comment by Kvasenok** [comment]
Пробовал переустановить интеграцию. Теперь не получается добавить чайник. Интеграция его видит, судя по всему модель определяется как RFS-KKL004, которая ворде есть в списке поддерживаемых, но придобавлении вылетает ошибка, что модель не поддерживается.
![skykettle1](https://user-images.githubusercontent.com/44749170/181448961-e272be70-e02e-44ef-b4c1-19c8962524f7.png)
![skykettle2](https://user-images.githubusercontent.com/44749170/181448996-c742b881-9abe-4310-bd26-aee1f107665e.png)

В логах пусто.

**Comment by Kvasenok** [comment]
> Тоже пришлось переустановить интеграцию и добавить модель "RFS-KKL004": MODELS_4. Наверное это в breaking changes вынести стоит.

У меня как раз модель определяется как RFS-KKL004. Видимо моя проблема в том, что такая модель не поддерживалась до Вашего коммита.
Я так понимаю, нужно ждать обновления интеграции?

**Comment by HepoH3** [comment]
> > Тоже пришлось переустановить интеграцию и добавить модель "RFS-KKL004": MODELS_4. Наверное это в breaking changes вынести стоит.
> 
> У меня как раз модель определяется как RFS-KKL004. Видимо моя проблема в том, что такая модель не поддерживалась до Вашего коммита. Я так понимаю, нужно ждать обновления интеграции?

Попробуйте на версию master перейти, должно заработать.

**Comment by ClusterM** [comment]
Да, установите версию из master

**Comment by TischenkoArseny** [comment]
Добавьте, пожалуйста, модель  "RFS-KKL00": MODELS_4, в оригинале G211S.

**Comment by ClusterM** [comment]
Окей

**Comment by ClusterM** [comment]
> RFS-KKL00

А это точно верное название модели? Пробовали переустановить интеграцию?

**Comment by HepoH3** [comment]
> > RFS-KKL00
> 
> А это точно верное название модели? Пробовали переустановить интеграцию?

Скорее всего нет, это до переустановки такое название выдает, у меня так же было.

**Comment by TischenkoArseny** [comment]
> > RFS-KKL00
> 
> А это точно верное название модели? Пробовали переустановить интеграцию?

Извините, мой косяк. После переустановки подтянулся под именем rkl002.
