### ISSUE TITLE
Отсутствует локализация

### ISSUE THREAD

**Issue by Kvasenok** [ClusterM/skykettle-ha#36]
У чайника режимы не переводятся на русский. Все режимы отображаются под своим английским названием типа "Boil", "Boil+Heat" и т.п., кроме режима "Выключено", т.к. это стандартный для ХА режим и его перевод подхватывается из самого ХА. 
Просто в файлах компонента в папке translations есть перевод режимов, но, видимо, он никак не подхватывается интеграцией.

**Comment by ClusterM** [comment]
Я пытался, но Home Assistant упорно отказывается подхватывать локализацию. Точнее она отображается, но не везде. Если кто-то подскажет мне, как это исправить, я буду очень благодарен.
