### ISSUE TITLE
"Пожалуйста убедитесь что чайник стоит на подставке и включен в розетку"

### ISSUE THREAD

**Issue by kktmaster** [ClusterM/skykettle-ha#4]
"Пожалуйста убедитесь что чайник стоит на подставке и включен  в розетку"
****************************** лог ****************************

Sun Feb  6 14:24:46 2022 daemon.err hass[2901]:   File "/etc/homeassistant/custom_components/skykettle/ble_scan.py", line 19, in run
Sun Feb  6 14:24:46 2022 daemon.err hass[2901]:     proc = subprocess.Popen(["timeout", "-s", "INT", f"{self.scan_time}s", "hcitool", "lescan"], stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=False)
Sun Feb  6 14:24:46 2022 daemon.err hass[2901]:   File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
Sun Feb  6 14:24:46 2022 daemon.err hass[2901]:   File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
Sun Feb  6 14:24:46 2022 daemon.err hass[2901]: FileNotFoundError: [Errno 2] No such file or directory: 'timeout'
*******************************************************************
root@OpenWrt:~# hcitool lescan
LE Scan ...
F5:82:FC:A8:9F:85 RK-G211S
33:BA:68:1A:26:D5 (unknown)
A4:C1:38:AD:2B:D4 (unknown)
69:8D:E7:4E:68:BF (unknown)

**Comment by ClusterM** [comment]
Try
```
opkg update
opkg install coreutils-timeout
```
I should add a check for timeout util.

**Comment by ClusterM** [comment]
Did it help?
