### ISSUE TITLE
Ошибка подключения cant_auth к SkyKettle RK-G214S (RFS-KKL003)

### ISSUE THREAD

**Issue by empenoso** [ClusterM/skykettle-ha#51]
При добавлении интеграции HA видит чайник SkyKettle RK-G214S (RFS-KKL003):

![Screenshot_18](https://github.com/ClusterM/skykettle-ha/assets/43311539/64bab959-a11c-4e86-9a80-15a219e7f48c)

Но не даёт подключиться к нему, выдаёт ошибку `cant_auth `.

Использую Home Assistant:
```
    Core 2023.12.4
    Supervisor 2023.12.0
    Operating System 11.2
    Пользовательский интерфейс 20231208.2
```

**Comment by empenoso** [comment]
Вопрос решился - подключился когда он был в режиме сопряжения.

**Comment by andysmr** [comment]
привет! у меня точно такая же проблема. Чайник обнаруживает, но не подключается. Может это что то с моей raspberry pi5?
