### ISSUE TITLE
Потерялась часть сенсоров (

### ISSUE THREAD

**Issue by Aleksey-Tuk** [ClusterM/skykettle-ha#52]
Теперь только можно вскипятить и все, выставить температуру нельзя, исчезло ( .Помогите

![Screenshot_1](https://github.com/ClusterM/skykettle-ha/assets/79055313/14ac93a4-365f-4052-8112-97a6bd0c18d1)

**Comment by Jekakv** [comment]
обновил HA?

**Comment by kai-zer-ru** [comment]
После обновления такая же беда. 2024.1

**Comment by WilJames** [comment]
в 2024.1 много констант убрали и поменяли, все сломалось, пришлось откатиться  пока.

**Comment by sashadeg** [comment]
Та же фигня. Основной switch работает, а water_heater.***** и некоторые другие перестали
![2024-01-05_21-48-55](https://github.com/ClusterM/skykettle-ha/assets/63294695/f5c1a1d1-5bb8-42be-a889-ab00ea8f3a99)

**Comment by Aleksey-Tuk** [comment]
Разрабочики починят интеграцию или нет?  А то как то не очень

**Comment by Aleksey-Tuk** [comment]
> обновил ХА?

да

**Comment by sashadeg** [comment]
> Разрабочики починят интеграцию или нет? А то как то не очень. У меня всё окончательно сломалось, теперь даже чайник не видит (

Будем надеяться. На сколько я понимаю, Лёша один её разрабатывал. Не может же он резко подорваться и бежать все исправлять. И так на чистом энтузиазме все.

**Comment by M0DDer** [comment]
Тоже очень жду, откатился пока назад

**Comment by sashadeg** [comment]
Закрывайте тему. В 2024.1.1 все исправили.

**Comment by M0DDer** [comment]
В  2024.1.3 опять не работает

**Comment by kai-zer-ru** [comment]
> В 2024.1.3 опять не работает

У меня всё работает, 2024.1.3
