### ISSUE TITLE
Ошибка в 2.5

### ISSUE THREAD

**Issue by X-rick-z** [ClusterM/skykettle-ha#67]
Не удалось выполнить действие water_heater.turn_on. Entity water_heater.skykettle_rfs_kkl003 does not support this service
![Screenshot_20240907_084906_io homeassistant companion android_edit_280080287539561](https://github.com/user-attachments/assets/596efbb9-38ee-49d1-b824-d99fdac504de)

**Comment by ops244** [comment]
такая-же беда
INTERNAL_ERROR: Failed to execute action for instance on (devices.capabilities.on_off) of water_heater.skykettle_rk_g200s: HomeAssistantError('Entity water_heater.skykettle_rk_g200s does not support this service.

**Comment by X-rick-z** [comment]
По всей видимости это связано не с апдейтом интеграции до 2.5, а с последним обновлением самого home assistant

**Comment by ops244** [comment]
верно, до обновления все работало, только вот что сейчас делать? ждать фикса от home assistant или теперь там все так и останется и ждать фикса от вас?)

**Comment by X-rick-z** [comment]
Пришлось везде менять water.heater на switch
А так не знаю, кого ждать, исправят ли или насовсем для бойлера отменили функцию он/офф

**Comment by leyalate35** [comment]
сделайте пожалуйста фикс для таких не опытных, как я)

**Comment by ops244** [comment]
он кстати только через яндекс не работает, если на компе нажимать - все работает как и раньше...

**Comment by ClusterM** [comment]
Похоже, разработчики Home Assistant убрали функции on/off у чайников :( Они и раньше-то недокументированы были. Теперь только через смену режима.
```
sequence:
  - service: water_heater.set_operation_mode
    data:
      operation_mode: Boil
    target:
      entity_id: water_heater.skykettle_rk_g211
```

Что же делать с Яндексом/Алисой пока непонятно. Яндекс не умеет в режимы чайника, только температуру выставлять. Сейчас можно говорить:
* Алиса, чайник на 100 градусов - кипячение
* Алиса, чайник на XX градусов - подогрев до XX градусов и удержание
* Алиса, чайник на 25 градусов - выключить чайник

Можно пока создать сценарий с фразами как временное решение. Надо будет это обсудить с автором интеграции Yandex Start Home.

**Comment by ops244** [comment]
в принципе достаточно было в configuration.yaml внести это и работает как прежде:

yandex_smart_home:
  entity_config:
    water_heater.skykettle_rk_g200s:
      name: Чайник
      room: Кухня
      type: devices.types.cooking.kettle
      turn_on:
        service: switch.turn_on
        entity_id: switch.skykettle_rk_g200s
      turn_off:
        service: switch.turn_off
        entity_id: switch.skykettle_rk_g200s

**Comment by X-rick-z** [comment]
> Похоже, разработчики Home Assistant убрали функции on/off у чайников :(

Ну вообще то не у чайников, а в домене water_heater. 

Через action: switch. turn_on (или off) без проблем. 
Вот только везде, где раньше был домен менять на свитч конечно грустно.

С Алисой ещё интереснее, у меня сценарий в ней есть с нестандартной фразой, так она говорит не смогла выполнить, но чайник включается

**Comment by ClusterM** [comment]
> > Похоже, разработчики Home Assistant убрали функции on/off у чайников :(
> 
> Ну вообще то не у чайников, а в домене water_heater. (Имхо)
> 
> Через action: switch. turn_on (или off) без проблем. Вот только везде, где раньше был домен менять на свитч конечно грустно.
> 
> С Алисой ещё интереснее, у меня сценарий в ней есть с нестандартной фразой, так она говорит не смогла выполнить, но чайник включается

Я это и имел в виду :)



> в принципе достаточно было в configuration.yaml внести это и работает как прежде:
> 
> yandex_smart_home: entity_config: water_heater.skykettle_rk_g200s: name: Чайник room: Кухня type: devices.types.cooking.kettle turn_on: service: switch.turn_on entity_id: switch.skykettle_rk_g200s turn_off: service: switch.turn_off entity_id: switch.skykettle_rk_g200s

О, класс! Спасибо!

**Comment by Danstiv** [comment]
Действительно не документированы, ну [что-то](https://github.com/clusterM/skykettle-ha/pull/72) сделал, вроде работает.
