### ISSUE TITLE
SkyKettle RK-G200S статус и температуру прокидывает в УДЯ, но не даёт включать

### ISSUE THREAD

**Issue by Mihail-A** [ClusterM/skykettle-ha#68]
SkyKettle RK-G200S статус и температуру прокидывает в УДЯ (Yandex Smart Home), но не даёт включать
После апгрейда HA на 2024.9.1.
![365149724-22ebd7b0-2dc0-4dc3-a851-73cae3635354](https://github.com/user-attachments/assets/2e059c1a-93be-4806-bd18-c648eda7de0d)

При этом,  не смотря на то, что чайник не включается командой "включить"/"выключить", его можно включить командой: "Алиса, нагрей чайник до ста градусов"

По ссылке есть ещё страдальцы https://github.com/dext0r/yandex_smart_home/issues/548

**Comment by ClusterM** [comment]
Дубликат #67.
