### ISSUE TITLE
Не работает одновременно с Bluetooth low energy monitor

### ISSUE THREAD

**Issue by Nesterovich2797** [ClusterM/skykettle-ha#9]
В окне установки "Автоматическое обнаружение чайника" после подтверждения появляется "Неизвестная ошибка, смотрите логи."

> Эта ошибка возникла в кастомной интеграции.
> 
> Регистратор : custom_components.skykettle.config_flow
> Источник: custom_components/skykettle/config_flow.py:118 Интеграция: SkyKettle Первое появление: 10:28:55 ( 1 вхождение) Последнее ведение журнала: 10:28:55
> ( документация , проблемы )
> 
> 
> 
> Трассировка (последний последний вызов): Файл "/config/custom_components/skykettle/config_flow.py", строка 97, в async_step_scan macs = await ble_scan(scan_time=BLE_SCAN_TIME) Файл "/config/custom_components/skykettle/ble_scan.py", строка 45, в ble_scan поднять исключение (ошибка) Исключение: не удалось установить параметры сканирования: ошибка ввода-вывода

**Comment by ClusterM** [comment]
Можно попробовать набрать в консоли:
```
sudo hciconfig hci1 down
sudo hciconfig hci1 up
```
Где вместо `hci1` ваш Bluetooth интерфейс.

**Comment by Nesterovich2797** [comment]
У меня работала интеграция Ready4sky. 
А так же работает Bluetooth low energy monitor. Все успешно подтягивают bluetooth

**Comment by ClusterM** [comment]
> работает Bluetooth low energy monitor

Скорее всего как раз конфликт с ним. Попробуйте его временно отключить.

**Comment by Nesterovich2797** [comment]
Временное отключение интеграции позволило подключить чайник. Но может получиться сделать чтобы 2 интеграции работали одновременно с одним Bluetooth устройством?

**Comment by ClusterM** [comment]
> Временное отключение интеграции позволило подключить чайник. Но может получиться сделать чтобы 2 интеграции работали одновременно с одним Bluetooth устройством?

Попробую подумать, но скорее всего это ограничение Linux на низкоуровневую работу с Bluetooth.

**Comment by Nesterovich2797** [comment]
Ready4sky и Bluetooth low energy monitor работают вместе на одном Bluetooth

**Comment by ClusterM** [comment]
Попробую их подружить, но попозже.

**Comment by Magalex2x14** [comment]
@ClusterM приветствую! Если нужны будут подробности о работе ble_monitor, я с радостью отвечу.

**Comment by Disperion** [comment]
> @ClusterM приветствую! Если нужны будут подробности о работе ble_monitor, я с радостью отвечу.

Приветствую! Поделитесь информацией по решению проблемы?

**Comment by vsimanin** [comment]
Такая же ошибка. Будет ли исправление?(

**Comment by ClusterM** [comment]
Пожалуйста, установите Home Assistant 2022.8.1 или новее и попробуйте версию из master. Она теперь работает через новую интеграцию "Bluetooth", так что убедитесь, что она включена и работает.

**Comment by vsimanin** [comment]
> not work!:(
@ClusterM 
![Screenshot_20220813-133244](https://user-images.githubusercontent.com/9263449/184479901-1e881cd6-363f-45a8-8031-858f86e7a8aa.jpg)
![Screenshot_20220813-133250](https://user-images.githubusercontent.com/9263449/184479902-895ec551-51b9-4427-8e94-e326d74e0f0a.jpg)

**Comment by ClusterM** [comment]
> not work!:(

ready4sky is not my integration. My is **skykettle**.

**Comment by vsimanin** [comment]
@ClusterM  sorry, i'm broken;)

Version 1.7 does not work.  I choose the auto interface or directly bluetooth 0. Then I confirm that the kettle is turned on and an error immediately appears.

![Screenshot_20220814-223624](https://user-images.githubusercontent.com/9263449/184552266-efcbb0a8-4a77-47f8-8f99-a6b7b486e831.jpg)

**Comment by ClusterM** [comment]
> @ClusterM  sorry, i'm broken;)
> 
> Version 1.7 does not work.  I choose the auto interface or directly bluetooth 0. Then I confirm that the kettle is turned on and an error immediately appears.
> 
> ![Screenshot_20220814-223624](https://user-images.githubusercontent.com/9263449/184552266-efcbb0a8-4a77-47f8-8f99-a6b7b486e831.jpg)
> 

I'm talking about version 2.0, from master.

**Comment by vsimanin** [comment]
@ClusterM very good work! Thanks, i love you ;))
